[2025-07-30T11:17:47.040+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T11:17:47.258+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Premier_dag.scraping_group.scrapy_Amploi_senegal manual__2025-07-30T11:17:30.207650+00:00 [queued]>
[2025-07-30T11:17:47.282+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Premier_dag.scraping_group.scrapy_Amploi_senegal manual__2025-07-30T11:17:30.207650+00:00 [queued]>
[2025-07-30T11:17:47.282+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-30T11:17:47.304+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scraping_group.scrapy_Amploi_senegal> on 2025-07-30 11:17:30.207650+00:00
[2025-07-30T11:17:47.312+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2025-07-30T11:17:47.316+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Premier_dag', 'scraping_group.scrapy_Amploi_senegal', 'manual__2025-07-30T11:17:30.207650+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/PremierDagLake.py', '--cfg-path', '/tmp/tmpquzwy9rr']
[2025-07-30T11:17:47.320+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask scraping_group.scrapy_Amploi_senegal
[2025-07-30T11:17:47.342+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-30T11:17:47.418+0000] {task_command.py:426} INFO - Running <TaskInstance: Premier_dag.scraping_group.scrapy_Amploi_senegal manual__2025-07-30T11:17:30.207650+00:00 [running]> on host 03609ac50de5
[2025-07-30T11:17:47.593+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Premier_dag' AIRFLOW_CTX_TASK_ID='scraping_group.scrapy_Amploi_senegal' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T11:17:30.207650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T11:17:30.207650+00:00'
[2025-07-30T11:17:47.595+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T11:17:47.596+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T11:17:47.597+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/scrapjob/spiders && scrapy crawl emploisenegal']
[2025-07-30T11:17:47.613+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T11:17:47.616+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/scrapjob/spiders: No such file or directory
[2025-07-30T11:17:47.617+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-30T11:17:47.618+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T11:17:47.633+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-30T11:17:47.641+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Premier_dag, task_id=scraping_group.scrapy_Amploi_senegal, execution_date=20250730T111730, start_date=20250730T111747, end_date=20250730T111747
[2025-07-30T11:17:47.666+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task scraping_group.scrapy_Amploi_senegal (Bash command failed. The command returned a non-zero exit code 1.; 72)
[2025-07-30T11:17:47.689+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T11:17:47.729+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T11:17:47.733+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
